language: generic

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-elisp/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install emacs-snapshot

script:
  - emacs-snapshot --version
  - make

